# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://spot.upi.edu/mhs/monitoring/2210008138/497731")
    self.driver.set_window_size(677, 783)
    self.driver.find_element(By.ID, "username").send_keys("2001657")
    self.driver.find_element(By.ID, "password").send_keys("")
    self.driver.find_element(By.NAME, "submit").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(3)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(3)")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(3)").text == "ALI AZIZ FADILLAH"
    elements = self.driver.find_elements(By.CSS_SELECTOR, "tr:nth-child(5) .fa")
    assert len(elements) > 0
    dropdown = self.driver.find_element(By.NAME, "id_pt")
    dropdown.find_element(By.XPATH, "//option[. = 'Pertemuan 3']").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".font-light").text == "PERTEMUAN 3"
  
